name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  flutter_localizations:      # ← ADD THIS
    sdk: flutter
  intl: ^0.20.2 
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true 

  assets:
    - assets/images/museum.png
    - assets/images/gallery1.png
    - assets/images/gallery2.png
    - assets/images/gallery3.jpg
    - assets/images/gallery4.webp

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-Bold.ttf
          weight: 700

    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600