// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ8Vm74Usqm8lXL1Rh3Z5n2z4QYQAlyV0',
    appId: '1:288626687274:web:8f17fe143d1a3aba64b253',
    messagingSenderId: '288626687274',
    projectId: 'egypt-tourism-guide',
    authDomain: 'egypt-tourism-guide.firebaseapp.com',
    storageBucket: 'egypt-tourism-guide.firebasestorage.app',
    measurementId: 'G-6CHQ7M9X3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARijbkvptGXfAvagw58tr0wvgXAXnPb3o',
    appId: '1:288626687274:android:545115a0e240f7fe64b253',
    messagingSenderId: '288626687274',
    projectId: 'egypt-tourism-guide',
    storageBucket: 'egypt-tourism-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8iO8FIYS3vo_Q1C9AtTnF3wgDZrFBjlE',
    appId: '1:288626687274:ios:58b21729d0c272d764b253',
    messagingSenderId: '288626687274',
    projectId: 'egypt-tourism-guide',
    storageBucket: 'egypt-tourism-guide.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8iO8FIYS3vo_Q1C9AtTnF3wgDZrFBjlE',
    appId: '1:288626687274:ios:58b21729d0c272d764b253',
    messagingSenderId: '288626687274',
    projectId: 'egypt-tourism-guide',
    storageBucket: 'egypt-tourism-guide.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ8Vm74Usqm8lXL1Rh3Z5n2z4QYQAlyV0',
    appId: '1:288626687274:web:f73214b5222b8d6464b253',
    messagingSenderId: '288626687274',
    projectId: 'egypt-tourism-guide',
    authDomain: 'egypt-tourism-guide.firebaseapp.com',
    storageBucket: 'egypt-tourism-guide.firebasestorage.app',
    measurementId: 'G-HP2Z5KJYN2',
  );
}
